name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  validate:
    name: Validate Renovate configuration file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate
        uses: rinchsan/renovate-config-validator@v0.2.0
        with:
          pattern: 'default.json'
